site_name: SuperFlow.inc
theme:
  name: material

nav:
  - Home: index.md
  - Blog:
      - Blog Home: blog/index.md
      - AI-Agent: blog/ai-agent.md
      - Planning: blog/ai-planning.md
      - 募集要項: blog/recruit.md
